"""Deprecated compatibility shim.

Canonical configuration now lives in ``oswap_config.py``. Do not edit this file.
It remains temporarily so older imports do not break during the OSWAP migration.
"""
from oswap_config import *  # noqa: F401,F403

if __name__ == "__main__":
    raise SystemExit("config.py is compatibility-only; run: python oswap_config.py --help")
